services:
  - type: web
    name: pterodactyl-panel
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: 'docker build -t pterodactyl-panel .'
    startCommand: 'docker run -p 80:80 -p 443:443 pterodactyl-panel'
    plan: free
    envVars:
      - key: DATABASE_URL
        value: mysql://ptero:strongpassword@pterodactyl-mysql:3306/panel
      - key: REDIS_URL
        value: redis://pterodactyl-redis:6379
      - key: APP_URL
        value: https://your-panel.onrender.com
      - key: APP_TIMEZONE
        value: UTC

  - type: mysql
    name: pterodactyl-mysql
    plan: free
    databaseName: panel
    user: ptero
    password: strongpassword

  - type: redis
    name: pterodactyl-redis
    plan: free
    redisMemory: 256MB
